# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "giozhrukzcqoopssegby"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a table or view without. Limits payload size for accidental or
# malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version_num;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Configure one of the supported pooler modes: `transaction`, `session`.
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 20
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv6)
# ip_version = "IPv6"
# The maximum length in bytes of HTTP request headers. (default: 4096)
# max_header_length = 4096

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://127.0.0.1:54321"
# OpenAI API Key to use for Supabase AI features.
openai_api_key = "env(OPENAI_API_KEY)"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth can be redirected to.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true
# Allow/disallow anonymous sign-ins to your project.
enable_anonymous_sign_ins = false
# Allow/disallow testing manual linking of accounts
enable_manual_linking = false

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false
# If enabled, users will need to reauthenticate or have logged in recently to change their password.
secure_password_change = false
# Controls the minimum amount of time that must pass before sending another signup confirmation or
# password reset email.
max_frequency = "1s"
# Number of characters used in the email OTP.
otp_length = 6
# Number of seconds before the email OTP expires (defaults to 86400 for a day).
otp_expiry = 86400

# Use a production-ready SMTP server
# [auth.email.smtp]
# host = "smtp.sendgrid.net"
# port = 587
# user = "apikey"
# pass = "env(SENDGRID_API_KEY)"
# admin_email = "admin@example.com"
# sender_name = "Admin"

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sending an SMS for phone confirmation.
template = "Your confirmation code is {{ .Token }}"
# Controls the minimum amount of time that must pass before sending another sms.
max_frequency = "5s"

# Use a production-ready SMS provider
# [auth.sms.twilio]
# enabled = true
# account_sid = "env(TWILIO_ACCOUNT_SID)"
# message_service_sid = "env(TWILIO_MESSAGE_SERVICE_SID)"
# auth_token = "env(TWILIO_AUTH_TOKEN)"

# Configure one of the supported SMS providers: `twilio`, `twilio_verify`, `messagebird`, `textlocal`, `vonage`
[auth.sms.vonage]
enabled = false
# api_key = "env(VONAGE_API_KEY)"
# api_secret = "env(VONAGE_API_SECRET)"
# from = "env(VONAGE_FROM)"

# Configure one of the supported captcha providers: `hcaptcha`, `recaptcha_v2`, `recaptcha_v3`, `turnstile`
[auth.captcha]
enabled = false
# Provider to use for captcha.
provider = "hcaptcha"
# Secret key for the captcha provider.
secret = "env(CAPTCHA_SECRET_KEY)"

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`, `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`, `twitter`, `slack`, `spotify`, `workos`, `zoom`.
[auth.external.apple]
enabled = false
client_id = "env(AUTH_APPLE_CLIENT_ID)"
secret = "env(AUTH_APPLE_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.azure]
enabled = false
client_id = "env(AUTH_AZURE_CLIENT_ID)"
secret = "env(AUTH_AZURE_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.bitbucket]
enabled = false
client_id = "env(AUTH_BITBUCKET_CLIENT_ID)"
secret = "env(AUTH_BITBUCKET_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.discord]
enabled = false
client_id = "env(AUTH_DISCORD_CLIENT_ID)"
secret = "env(AUTH_DISCORD_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.facebook]
enabled = false
client_id = "env(AUTH_FACEBOOK_CLIENT_ID)"
secret = "env(AUTH_FACEBOOK_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.github]
enabled = false
client_id = "env(AUTH_GITHUB_CLIENT_ID)"
secret = "env(AUTH_GITHUB_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.gitlab]
enabled = false
client_id = "env(AUTH_GITLAB_CLIENT_ID)"
secret = "env(AUTH_GITLAB_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.google]
enabled = false
client_id = "env(AUTH_GOOGLE_CLIENT_ID)"
secret = "env(AUTH_GOOGLE_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.keycloak]
enabled = false
client_id = "env(AUTH_KEYCLOAK_CLIENT_ID)"
secret = "env(AUTH_KEYCLOAK_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.linkedin]
enabled = false
client_id = "env(AUTH_LINKEDIN_CLIENT_ID)"
secret = "env(AUTH_LINKEDIN_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.notion]
enabled = false
client_id = "env(AUTH_NOTION_CLIENT_ID)"
secret = "env(AUTH_NOTION_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.twitch]
enabled = false
client_id = "env(AUTH_TWITCH_CLIENT_ID)"
secret = "env(AUTH_TWITCH_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.twitter]
enabled = false
client_id = "env(AUTH_TWITTER_CLIENT_ID)"
secret = "env(AUTH_TWITTER_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.slack]
enabled = false
client_id = "env(AUTH_SLACK_CLIENT_ID)"
secret = "env(AUTH_SLACK_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.spotify]
enabled = false
client_id = "env(AUTH_SPOTIFY_CLIENT_ID)"
secret = "env(AUTH_SPOTIFY_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.workos]
enabled = false
client_id = "env(AUTH_WORKOS_CLIENT_ID)"
secret = "env(AUTH_WORKOS_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[auth.external.zoom]
enabled = false
client_id = "env(AUTH_ZOOM_CLIENT_ID)"
secret = "env(AUTH_ZOOM_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure, or any other third-party OIDC providers.
url = ""

[edge_runtime]
enabled = true
# Configure one of the supported request policies: `oneshot`, `per_worker`
# Use `oneshot` for hot-reloading, or `per_worker` for load testing.
policy = "oneshot"
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of the supported backends: `postgres`, `bigquery`
backend = "postgres"

# Experimental features may be deprecated any time
[experimental]
# Configures Postgres storage engine to use OrioleDB (S3)
orioledb_version = ""
# Configures S3 bucket URL, eg. <bucket_name>.s3-<region>.amazonaws.com
s3_host = "env(S3_HOST)"
# Configures S3 bucket region, eg. us-east-1
s3_region = "env(S3_REGION)"
# Configures S3 bucket name, eg. my-orioledb-bucket
s3_bucket = "env(S3_BUCKET)"
# Configures AWS_ACCESS_KEY_ID for S3 bucket
s3_access_key = "env(S3_ACCESS_KEY)"
# Configures AWS_SECRET_ACCESS_KEY for S3 bucket
s3_secret_key = "env(S3_SECRET_KEY)"
# Configures AWS_SESSION_TOKEN for S3 bucket
s3_session_token = "env(S3_SESSION_TOKEN)"

[functions.file-storage]
# Allows downloading of folders
enabled = true

[functions.http]
# Allow http requests, eg. for calling 3rd party APIs
enabled = true

# Configure one of the supported pools: `none`, `transaction`
[db.pooler_pools]

[db.pooler_pools.0]
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100
ignore_startup_parameters = "extra_float_digits,options"

[db.pooler_pools.1]
pool_mode = "session"
default_pool_size = 5
max_client_conn = 200
ignore_startup_parameters = "extra_float_digits,options"

[db.seed]
# If enabled, seeds the database after migrations during a db reset.
enabled = true
# Sql file to seed database
cmd = "psql -d postgres -U postgres -f seed.sql"